library(mvabund)
x <- as.matrix(read.csv('./genus80_top30.csv',row.names=1))
x <- as.matrix(read.csv('../feature_tables/52N_genus_t80_selbal.csv',row.names=1))
x <- as.matrix(read.csv('./rel.csv',row.names=1))
meta <- as.data.frame(read.csv('../meta/meta52_current.csv',row.names=1))

x <- as.mvabund(x)
plot(x)
meanvar.plot(x)
variables <- c('Age', 'APACHE', 'Gender', 'ARDS')
m <- meta[variables]
m <- as.matrix(m)

mod1 <- manyglm(x ~  mmi , data=meta, family = 'negative binomial',composition = TRUE)
plot(mod2)
mod1 <- manyglm(x ~ mmi + APACHE + Age , data=meta, family = 'negative binomial',composition = TRUE)
mod2 <- manyglm(x ~ Age , data=meta, family = 'negative binomial',composition = FALSE)
mod2 <- manyglm(x ~ mmi + Age +  as.factor(Sepsis3) + as.factor(Vancomycin) + as.factor(Zosyn) + as.factor(Cipro) , data=meta, family = 'negative binomial',composition = TRUE)
mod2 <- manyglm(x ~ mmi , data=meta, family = 'negative binomial',composition = FALSE)
anov <- anova.manyglm(mod1,p.uni="adjusted")
anov <- summary.manyglm(mod1,p.uni="adjusted")
a <- colnames(x)
summary.manyglm(mod1)
names(anov)
